"""add_charge_model

Revision ID: 56bbe7fdd5ab
Revises: 0001_create_webhook_requests
Create Date: 2026-01-24 11:40:24.789958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56bbe7fdd5ab'
down_revision: Union[str, None] = '0001_create_webhook_requests'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('correlation_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('customer_tax_id', sa.String(length=20), nullable=False),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('br_code', sa.Text(), nullable=True),
    sa.Column('qr_code_url', sa.Text(), nullable=True),
    sa.Column('payment_link_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correlation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('charges')
    # ### end Alembic commands ###
