"""add_expires_at_to_charge

Revision ID: abe3a969bc05
Revises: 56bbe7fdd5ab
Create Date: 2026-01-24 12:05:07.722874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abe3a969bc05'
down_revision: Union[str, None] = '56bbe7fdd5ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charges', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('charges', 'expires_at')
    # ### end Alembic commands ###
