"""add_ploomes_ids_to_charge

Revision ID: fb5ab4c2c985
Revises: abe3a969bc05
Create Date: 2026-01-24 17:27:01.522186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb5ab4c2c985'
down_revision: Union[str, None] = 'abe3a969bc05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charges', sa.Column('ploomes_contact_id', sa.Integer(), nullable=True))
    op.add_column('charges', sa.Column('ploomes_deal_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('charges', 'ploomes_deal_id')
    op.drop_column('charges', 'ploomes_contact_id')
    # ### end Alembic commands ###
